
#ifndef _saAutoRegress
#define _saAutoRegress

#define SA_AUTOREGRESSION_DEFAULTNUMCOEFS 3
#define SA_AUTOREGRESSION_MAXNUMCOEFS 16

#define SA_AUTOREGRESSION_LEASTSQUARES 0
#define SA_AUTOREGRESSION_MAXENTROPY 1

#endif
